pdd=int(input("barras de pan del día: "))
pNOdd=int(input("barras de pan que NO son del día: "))
total=float((pdd+pNOdd)*3.49)
totdes=float((pdd*3.49)+(pNOdd*2.094))
descuento=int(total-totdes)
print()
print("El monto es de: $",total)
print()
print("Descuento: $", descuento)
print("----------------")
print("TOTAL: $", round(totdes, 3))
